=== redpanda-ai/meerkat_webservice_schema/schema_output.json
{
	"$schema" : "http://json-schema.org/draft-04/schema#",
	"title" : "meerkat_categorize output",
	"definitions" : {
		"no_match_found" : {
			"type" : "object",
			"properties" : {
				"transaction_id" : { "type" : "number" },
				"is_physical_merchant" : { "enum" : [ true, false ] },
				"match_found" : { "enum" : [ false ] }
			},
			"required": [ "transaction_id", "is_physical_merchant", "match_found" ]
		},
		"physical_merchant_response" : {
			"type" : "object",
			"properties" : {
				"transaction_id" : { "type" : "number" },
				"is_physical_merchant" : { "enum" : [ true ] },
				"match_found" : { "enum" : [ true ] },
				"merchant_name" : { "type" : "string" },
				"store_id" : { "type" : "string" },
				"category_labels" : {
					"type" : "array",
					"items" : {
						"type": "string"
					}
				},
				"source" : { "enum": [ "FACTUAL", "OTHER" ] },
				"source_merchant_id" : { "type" : "string" },
				"street" : { "type" : "string" },
				"city" : { "type" : "string" },
				"state" : { "type" : "string" },
				"country" : { "type" : "string", "maxLength" : 2, "minLength" : 2 },
				"postal_code" : { "type" : "string" }
			},
			"required": [ "transaction_id", "is_physical_merchant", "match_found", "merchant_name", "source_merchant_id", "country" ]
		},
		"non_physical_merchant_response" : {
			"type" : "object",
			"properties" : {
				"transaction_id" : { "type" : "number" },
				"is_physical_merchant" : { "enum" : [ false ] },
				"merchant_name" : { "type" : "string" }
			},
			"required": [ "transaction_id", "is_physical_merchant", "merchant_name" ]
		},
		"non_merchant_category_response" : {
			"type" : "object",
			"properties" : {
				"transaction_id" : { "type" : "number" },
				"is_physical_merchant" : { "enum" : [ false ] },
				"category_labels" : {
					"type" : "array",
					"items" : {
						"type": "string"
					}
				}
			},
			"required": [ "transaction_id", "is_physical_merchant", "category_labels" ]
		}
	},
	"description": "A schema for defining output from 'meerkat_categorize'",
	"type" : "object",
	"properties" : {
		"cobrand_id" : {
			"description" : "Yodlee's number to uniquely identify the cobrand",
			"type" : "number"
		},
		"user_id" : {
			"description" : "Yodlee's number to uniquely identify a user within a cobrand",
			"type" : "number"
		},
		"container" : { "enum" : [ "bank", "card" ] },
		"transaction_list" : {
			"description" : "An array containing at least one of the following response types.",
			"type" : "array",
			"items" : {
				"oneOf": [
					{"$ref": "#/definitions/physical_merchant_response"},
					{"$ref": "#/definitions/no_match_found"},
					{"$ref": "#/definitions/non_physical_merchant_response"},
					{"$ref": "#/definitions/non_merchant_category_response"}
				]
			},
			"minItems": 1,
			"uniqueItems": true
		}
	},
	"required": ["cobrand_id", "user_id", "container", "transaction_list"]
}

=== redpanda-ai/meerkat_webservice_schema/example_output.json
{
	"cobrand_id" : 1234,
	"user_id" : 2345,
	"container" : "card",
	"transaction_list" : [
		{
			"transaction_id" : 1,
			"is_physical_merchant" : true,
			"match_found" : true,
			"merchant_name" : "Safeway",
			"store_id" : "#12",
			"category_labels" : ["Grocery", "Pharmacy"],
			"source" : "FACTUAL",
			"source_merchant_id" : "3ec075f0-33c2-11e4-8c21-0800200c9a66",
			"street" : "742 El Camino Real",
			"city" : "Sunnyvale",
			"state" : "CA",
			"country" : "US",
			"postal_code" : "94087"
		},
		{
			"transaction_id" : 2,
			"is_physical_merchant" : false,
			"category_labels" : ["bank_transfer"]
		},
		{
			"transaction_id" : 3,
			"is_physical_merchant" : false,
			"merchant_name" : "Amazon"
		},
		{
			"transaction_id" : 4,
			"is_physical_merchant" : true,
			"match_found" : false
		},
		{
			"transaction_id" : 5,
			"is_physical_merchant" : false,
			"match_found" : false
		}
	]
}
